mod github;
mod unicode;
mod util;

use std::collections::HashMap;
use std::fmt;
use std::fs;
use std::hash::Hasher;
use std::io;
use std::io::Write as _;
use std::path::PathBuf;

use anyhow::Result;

const HEADER: &str = "// Code generated by `cargo run --package generate`. DO NOT EDIT.\n";

fn main() -> Result<()> {
    let dir = PathBuf::from_iter([env!("CARGO_WORKSPACE_DIR"), "src", "gen"]);

    let unicode_data = unicode::build()?;
    let github_data = github::build()?;
    let mut unicode_map = HashMap::new();
    let mut shortcode_map = HashMap::new();

    let cwd = std::env::current_dir()?;
    fs::remove_dir_all(&dir).ok();
    fs::create_dir_all(&dir)?;

    let path = dir.join("mod.rs");
    let mut f = fs::File::create(&path)?;
    writeln!(f, "{HEADER}")?;
    writeln!(f, "#![cfg_attr(rustfmt, rustfmt::skip)]\n")?;
    writeln!(f, "pub mod shortcode;")?;
    writeln!(f, "pub mod unicode;\n")?;
    writeln!(
        f,
        "use crate::{{Emoji, Group, SkinTone, UnicodeVersion}};\n"
    )?;
    write_emojis_slice(
        &mut f,
        &unicode_data,
        &github_data,
        &mut unicode_map,
        &mut shortcode_map,
    )?;
    eprintln!("generated: {}", path.strip_prefix(&cwd)?.display());

    let path = dir.join("unicode.rs");
    let mut f = fs::File::create(&path)?;
    writeln!(f, "{HEADER}")?;
    write_phf_map(&mut f, unicode_map)?;
    eprintln!("generated: {}", path.strip_prefix(&cwd)?.display());

    let path = dir.join("shortcode.rs");
    let mut f = fs::File::create(&path)?;
    writeln!(f, "{HEADER}")?;
    write_phf_map(&mut f, shortcode_map)?;
    eprintln!("generated: {}", path.strip_prefix(&cwd)?.display());

    Ok(())
}

fn write_emojis_slice<W: io::Write>(
    w: &mut W,
    unicode_data: &unicode::ParsedData,
    github_data: &github::ParsedData,
    unicode_map: &mut HashMap<String, String>,
    shortcode_map: &mut HashMap<String, String>,
) -> Result<()> {
    let mut default_skin_tone_index = 0;

    writeln!(w, "pub const EMOJIS: &[Emoji] = &[")?;
    for (i, emoji) in unicode_data.iter().enumerate() {
        if matches!(emoji.skin_tone, Some(unicode::SkinTone::Default)) {
            default_skin_tone_index = i;
        }
        write!(w, "    ")?;
        write_emoji_struct(
            w,
            github_data,
            emoji,
            default_skin_tone_index,
            unicode_data[default_skin_tone_index].skin_tones,
        )?;
        writeln!(w, ",")?;

        unicode_map.insert(emoji.as_str().to_owned(), i.to_string());
        for v in &emoji.variations {
            assert!(unicode_map.insert(v.to_owned(), i.to_string()).is_none());
        }

        if let Some(aliases) = &github_data.get(emoji.as_str()) {
            for alias in &**aliases {
                assert!(shortcode_map
                    .insert(alias.to_owned(), i.to_string())
                    .is_none());
            }
        }
    }

    writeln!(w, "];")?;
    Ok(())
}

fn write_emoji_struct<W: io::Write>(
    w: &mut W,
    github_data: &github::ParsedData,
    emoji: &unicode::Emoji,
    default_skin_tone_index: usize,
    skin_tone_count: usize,
) -> Result<()> {
    let e = emoji.as_str();
    let group = emoji.entry.group;
    let name = &emoji.entry.name;
    let uv = &emoji.entry.unicode_version;
    write!(
        w,
        "Emoji {{ emoji: \"{e}\", name: \"{name}\", unicode_version: {uv:?}, group: Group::{group:?}",
    )?;
    match emoji.skin_tone {
        Some(tone) => write!(
            w,
            ", skin_tone: Some(({default_skin_tone_index}, {skin_tone_count}, SkinTone::{tone:?}))",
        )?,
        None => write!(w, ", skin_tone: None")?,
    }
    match &github_data.get(e) {
        Some(github) => write!(w, ", aliases: Some(&{:?}) }}", &github)?,
        None => write!(w, ", aliases: None }}")?,
    }
    Ok(())
}

fn write_phf_map<W: io::Write>(w: &mut W, map: HashMap<String, String>) -> Result<()> {
    /// By default phf formats string keys using the Rust debug implementation,
    /// which uses escape sequences for some Unicode code points. But this means
    /// as the Rust version is updated the generated code will change. None of
    /// the keys in our maps contain characters that would cause invalid Rust
    /// syntax so we use a custom type that formats the strings as-is.
    #[derive(Hash, PartialEq, Eq)]
    struct NoEscapeStr<'a>(&'a str);

    impl phf_shared::PhfHash for NoEscapeStr<'_> {
        fn phf_hash<H: Hasher>(&self, state: &mut H) {
            phf_shared::PhfHash::phf_hash(self.0, state);
        }
    }
    impl phf_shared::FmtConst for NoEscapeStr<'_> {
        fn fmt_const(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            write!(f, "\"{}\"", self.0)
        }
    }

    write!(w, "pub static MAP: phf::Map<&'static str, usize> = ")?;
    let mut gen = phf_codegen::Map::new();
    for (key, value) in &map {
        gen.entry(NoEscapeStr(key), value);
    }
    writeln!(w, "{};", gen.phf_path("phf").build())?;
    Ok(())
}
